### ISSUE TITLE
Arreglar GitHub Actions

### ISSUE THREAD

**Issue by 4lv4r0k** [decide-part-osuna/decide-osuna#55]

**Comment by pabsanper** [comment]
Se han creado 2 archivos para GitHub Actions, uno correspondiente al analisis de requisitos, despligue en local del proyecto, test y analisis de codacy; y el otro corresponiente al analisis de CodeQL, para identificar vulnerabilidades y errores en el código.
Tambien sirve para automatizar las verificaciones de seguridad.
